### ISSUE TITLE
[2] Add Docker

### ISSUE THREAD

**Issue by Emeshka** [Emeshka/bbcad-web#3]

**Comment by pratikkumar2210** [comment]
I am willing to work on it. Kindly assign this task to me.

**Comment by Emeshka** [comment]
Update: the database will be a separate SaaS entity, so no need to use `docker-compose`.

**Comment by Emeshka** [comment]
Update: due to architrecture review it was decided to serve the React app statically on AWS S3 bucket, thus no Docker required anymore. The issue will be closed.
